export const HERD_STATIC_DATA = [
  {
    'tag': '41626',
    'purpose': 'dairy',
    'category': 'cow',
    'breed': 'FR',
    'dob': '16/02/2014',
    'brand': '626',
    'inCalf': false,
    'served': false,
    'calved': true,
    'calfDate': '12/03/2018',
    'boughtIn': false,
    'boughtDate': null,
    'bornOnFarm': true,
    'movedOut': false
  },
  {
    'tag': '41051',
    'purpose': 'beef',
    'category': 'bull',
    'breed': 'AAX',
    'dob': '10/03/2014',
    'brand': '51',
    'boughtIn': false,
    'boughtDate': null,
    'bornOnFarm': true,
    'movedOut': false
  },
  {
    'tag': '21281',
    'purpose': 'dairy',
    'category': 'cow',
    'breed': 'FR',
    'dob': '15/02/2016',
    'brand': '281',
    'inCalf': false,
    'served': false,
    'calved': true,
    'calfDate': '12/03/2018',
    'boughtIn': false,
    'boughtDate': null,
    'bornOnFarm': true,
    'movedOut': false
  },
  {
    'tag': '30412',
    'purpose': 'dairy',
    'category': 'cow',
    'breed': 'FRX',
    'dob': '03/02/2010',
    'brand': '412',
    'inCalf': true,
    'served': false,
    'calved': false,
    'calfDate': null,
    'boughtIn': false,
    'boughtDate': null,
    'bornOnFarm': true,
    'movedOut': false
  },
  {
    'tag': '53911',
    'purpose': 'dairy',
    'category': 'cow',
    'breed': 'FR',
    'dob': '21/03/2015',
    'brand': '911',
    'inCalf': true,
    'served': false,
    'calved': false,
    'calfDate': null,
    'boughtIn': false,
    'boughtDate': null,
    'bornOnFarm': true,
    'movedOut': false
  },
  {
    'tag': '80332',
    'purpose': 'other',
    'category': 'cow',
    'breed': 'SIX',
    'dob': '15/04/2005',
    'brand': '332',
    'inCalf': true,
    'served': false,
    'calved': false,
    'calfDate': null,
    'boughtIn': false,
    'boughtDate': null,
    'bornOnFarm': true,
    'movedOut': false
  },
  {
    'tag': '51831',
    'purpose': 'dairy',
    'category': 'bull',
    'breed': 'FR',
    'dob': '17/02/2014',
    'brand': '831',
    'boughtIn': false,
    'boughtDate': null,
    'bornOnFarm': true,
    'movedOut': false
  },
  {
    'tag': '71342',
    'purpose': 'beef',
    'category': 'bull',
    'breed': 'BA',
    'dob': '05/05/2015',
    'brand': '342',
    'boughtDate': null,
    'bornOnFarm': true,
    'movedOut': false
  },
  {
    'tag': '31329',
    'purpose': 'beef',
    'category': 'bull',
    'breed': 'AAX',
    'dob': '17/05/2016',
    'brand': '329',
    'boughtIn': false,
    'boughtDate': null,
    'bornOnFarm': true,
    'movedOut': false
  },
  {
    'tag': '90027',
    'purpose': 'dairy',
    'category': 'cow',
    'breed': 'FR',
    'dob': '08/03/2016',
    'brand': '27',
    'inCalf': true,
    'served': false,
    'calved': false,
    'calfDate': null,
    'boughtIn': false,
    'boughtDate': null,
    'bornOnFarm': true,
    'movedOut': false
  },
  {
    'tag': '60758',
    'purpose': 'beef',
    'category': 'bull',
    'breed': 'BBX',
    'dob': '17/02/2014',
    'brand': '758',
    'boughtIn': false,
    'boughtDate': null,
    'bornOnFarm': true,
    'movedOut': false
  },
  {
    'tag': '10836',
    'purpose': 'dairy',
    'category': 'cow',
    'breed': 'FR',
    'dob': '13/12/2011',
    'brand': '836',
    'inCalf': false,
    'served': true,
    'calved': false,
    'calfDate': null,
    'boughtIn': false,
    'boughtDate': null,
    'bornOnFarm': true,
    'movedOut': false
  },
  {
    'tag': '20480',
    'purpose': 'dairy',
    'category': 'cow',
    'breed': 'FR',
    'dob': '08/04/2010',
    'brand': '480',
    'inCalf': false,
    'served': true,
    'calved': false,
    'calfDate': null,
    'boughtIn': false,
    'boughtDate': null,
    'bornOnFarm': true,
    'movedOut': false
  },
  {
    'tag': '91749',
    'purpose': 'dairy',
    'category': 'cow',
    'breed': 'FR',
    'dob': '01/04/2013',
    'brand': '749',
    'inCalf': false,
    'served': false,
    'calved': false,
    'calfDate': null,
    'boughtIn': false,
    'boughtDate': null,
    'bornOnFarm': true,
    'movedOut': false
  },
  {
    'tag': '90025',
    'purpose': 'beef',
    'category': 'bull',
    'breed': 'HEX',
    'dob': '08/01/2017',
    'brand': '25',
    'boughtIn': false,
    'boughtDate': null,
    'bornOnFarm': true,
    'movedOut': false
  },
  {
    'tag': '40488',
    'purpose': 'other',
    'category': 'cow',
    'breed': 'STX',
    'dob': '13/03/2016',
    'brand': '488',
    'inCalf': false,
    'served': false,
    'calved': true,
    'calfDate': '12/03/2018',
    'boughtIn': false,
    'boughtDate': null,
    'bornOnFarm': true,
    'movedOut': false
  },
  {
    'tag': '82030',
    'purpose': 'dairy',
    'category': 'cow',
    'breed': 'FRX',
    'dob': '18/02/2016',
    'brand': '30',
    'inCalf': true,
    'served': false,
    'calved': false,
    'calfDate': null,
    'boughtIn': false,
    'boughtDate': null,
    'bornOnFarm': true,
    'movedOut': false
  },
  {
    'tag': '21055',
    'purpose': 'other',
    'category': 'cow',
    'breed': 'AAX',
    'dob': '01/05/2016',
    'brand': '55',
    'inCalf': false,
    'served': true,
    'calved': false,
    'calfDate': null,
    'boughtIn': false,
    'boughtDate': null,
    'bornOnFarm': true,
    'movedOut': false
  },
  {
    'tag': '20849',
    'purpose': 'other',
    'category': 'cow',
    'breed': 'LM',
    'dob': '22/03/2016',
    'brand': '849',
    'inCalf': true,
    'served': false,
    'calved': false,
    'calfDate': null,
    'boughtIn': false,
    'boughtDate': null,
    'bornOnFarm': true,
    'movedOut': false
  },
  {
    'tag': '60486',
    'purpose': 'other',
    'category': 'cow',
    'breed': 'CHX',
    'dob': '01/02/2016',
    'brand': '486',
    'inCalf': false,
    'served': false,
    'calved': true,
    'calfDate': '12/03/2018',
    'boughtIn': false,
    'boughtDate': null,
    'bornOnFarm': true,
    'movedOut': false
  },
  {
    'tag': '30988',
    'purpose': 'dairy',
    'category': 'bull',
    'breed': 'FR',
    'dob': '22/03/2014',
    'brand': '988',
    'boughtIn': false,
    'boughtDate': null,
    'bornOnFarm': true,
    'movedOut': false
  },
  {
    'tag': '60890',
    'purpose': 'dairy',
    'category': 'cow',
    'breed': 'FR',
    'dob': '20/02/2014',
    'brand': '890',
    'inCalf': true,
    'served': false,
    'calved': false,
    'calfDate': null,
    'boughtIn': false,
    'boughtDate': null,
    'bornOnFarm': true,
    'movedOut': false
  },
  {
    'tag': '62156',
    'purpose': 'dairy',
    'category': 'bull',
    'breed': 'FR',
    'dob': '07/03/2015',
    'brand': '156',
    'boughtIn': false,
    'boughtDate': null,
    'bornOnFarm': true,
    'movedOut': false
  },
  {
    'tag': '90626',
    'purpose': 'beef',
    'category': 'bull',
    'breed': 'LMX',
    'dob': '08/01/2016',
    'brand': '626',
    'boughtIn': false,
    'boughtDate': null,
    'bornOnFarm': true,
    'movedOut': false
  },
  {
    'tag': '30366',
    'purpose': 'other',
    'category': 'cow',
    'breed': 'LMX',
    'dob': '22/11/2016',
    'brand': '366',
    'inCalf': false,
    'served': true,
    'calved': false,
    'calfDate': null,
    'boughtIn': false,
    'boughtDate': null,
    'bornOnFarm': true,
    'movedOut': false
  },
  {
    'tag': '80936',
    'purpose': 'beef',
    'category': 'bull',
    'breed': 'AU',
    'dob': '20/01/2017',
    'brand': '936',
    'boughtIn': false,
    'boughtDate': null,
    'bornOnFarm': true,
    'movedOut': false
  },
  {
    'tag': '81500',
    'purpose': 'beef',
    'category': 'bull',
    'breed': 'LMX',
    'dob': '18/04/2017',
    'brand': '500',
    'boughtIn': false,
    'boughtDate': null,
    'bornOnFarm': true,
    'movedOut': false
  },
  {
    'tag': '41227',
    'purpose': 'dairy',
    'category': 'bull',
    'breed': 'FRX',
    'dob': '11/02/2017',
    'brand': '227',
    'boughtIn': false,
    'boughtDate': null,
    'bornOnFarm': true,
    'movedOut': false
  },
  {
    'tag': '71024',
    'purpose': 'beef',
    'category': 'bull',
    'breed': 'LMX',
    'dob': '11/06/2016',
    'brand': '24',
    'boughtIn': false,
    'boughtDate': null,
    'bornOnFarm': true,
    'movedOut': false
  },
  {
    'tag': '40374',
    'purpose': 'other',
    'category': 'cow',
    'breed': 'HEX',
    'dob': '30/01/2005',
    'brand': '374',
    'inCalf': false,
    'served': false,
    'calved': false,
    'calfDate': null,
    'boughtIn': false,
    'boughtDate': null,
    'bornOnFarm': true,
    'movedOut': false
  },
  {
    'tag': '51080',
    'purpose': 'dairy',
    'category': 'cow',
    'breed': 'JEX',
    'dob': '19/02/2010',
    'brand': '80',
    'inCalf': false,
    'served': false,
    'calved': false,
    'calfDate': null,
    'boughtIn': false,
    'boughtDate': null,
    'bornOnFarm': true,
    'movedOut': false
  },
  {
    'tag': '31287',
    'purpose': 'dairy',
    'category': 'cow',
    'breed': 'FR',
    'dob': '17/01/2017',
    'brand': '287',
    'inCalf': false,
    'served': false,
    'calved': false,
    'calfDate': null,
    'boughtIn': false,
    'boughtDate': null,
    'bornOnFarm': true,
    'movedOut': false
  },
  {
    'tag': '40189',
    'purpose': 'other',
    'category': 'cow',
    'breed': 'CHX',
    'dob': '01/05/2009',
    'brand': '189',
    'inCalf': false,
    'served': false,
    'calved': true,
    'calfDate': '12/03/2018',
    'boughtIn': false,
    'boughtDate': null,
    'bornOnFarm': true,
    'movedOut': false
  },
  {
    'tag': '80813',
    'purpose': 'dairy',
    'category': 'cow',
    'breed': 'FR',
    'dob': '06/02/2009',
    'brand': '813',
    'inCalf': false,
    'served': false,
    'calved': true,
    'calfDate': '12/03/2018',
    'boughtIn': false,
    'boughtDate': null,
    'bornOnFarm': true,
    'movedOut': false
  },
  {
    'tag': '40660',
    'purpose': 'dairy',
    'category': 'cow',
    'breed': 'FR',
    'dob': '05/03/2015',
    'brand': '660',
    'inCalf': false,
    'served': false,
    'calved': true,
    'calfDate': '12/03/2018',
    'boughtIn': false,
    'boughtDate': null,
    'bornOnFarm': true,
    'movedOut': false
  },
  {
    'tag': '60313',
    'purpose': 'beef',
    'category': 'bull',
    'breed': 'CHX',
    'dob': '10/02/2015',
    'brand': '313',
    'boughtIn': false,
    'boughtDate': null,
    'bornOnFarm': true,
    'movedOut': false
  },
  {
    'tag': '70802',
    'purpose': 'dairy',
    'category': 'cow',
    'breed': 'FR',
    'dob': '13/02/2012',
    'brand': '802',
    'inCalf': false,
    'served': false,
    'calved': true,
    'calfDate': '12/03/2018',
    'boughtIn': false,
    'boughtDate': null,
    'bornOnFarm': true,
    'movedOut': false
  },
  {
    'tag': '91887',
    'purpose': 'beef',
    'category': 'bull',
    'breed': 'AAX',
    'dob': '19/02/2017',
    'brand': '887',
    'boughtIn': false,
    'boughtDate': null,
    'bornOnFarm': true,
    'movedOut': false
  },
  {
    'tag': '50695',
    'purpose': 'dairy',
    'category': 'cow',
    'breed': 'FR',
    'dob': '20/01/2012',
    'brand': '695',
    'inCalf': false,
    'served': false,
    'calved': true,
    'calfDate': '12/03/2018',
    'boughtIn': false,
    'boughtDate': null,
    'bornOnFarm': true,
    'movedOut': false
  },
  {
    'tag': '91287',
    'purpose': 'other',
    'category': 'cow',
    'breed': 'SIX',
    'dob': '14/09/2014',
    'brand': '287',
    'inCalf': false,
    'served': false,
    'calved': true,
    'calfDate': '12/03/2018',
    'boughtIn': false,
    'boughtDate': null,
    'bornOnFarm': true,
    'movedOut': false
  },
  {
    'tag': '60877',
    'purpose': 'beef',
    'category': 'bull',
    'breed': 'MO',
    'dob': '23/12/2015',
    'brand': '877',
    'boughtIn': false,
    'boughtDate': null,
    'bornOnFarm': true,
    'movedOut': false
  },
  {
    'tag': '81219',
    'purpose': 'other',
    'category': 'cow',
    'breed': 'AAX',
    'dob': '16/03/2014',
    'brand': '219',
    'inCalf': false,
    'served': false,
    'calved': false,
    'calfDate': null,
    'boughtIn': false,
    'boughtDate': null,
    'bornOnFarm': true,
    'movedOut': false
  },
  {
    'tag': '21387',
    'purpose': 'dairy',
    'category': 'cow',
    'breed': 'FR',
    'dob': '17/02/2015',
    'brand': '387',
    'inCalf': false,
    'served': false,
    'calved': false,
    'calfDate': null,
    'boughtIn': false,
    'boughtDate': null,
    'bornOnFarm': true,
    'movedOut': false
  },
  {
    'tag': '61587',
    'purpose': 'dairy',
    'category': 'cow',
    'breed': 'FR',
    'dob': '08/11/2014',
    'brand': '587',
    'inCalf': false,
    'served': false,
    'calved': false,
    'calfDate': null,
    'boughtIn': true,
    'boughtDate': '26/10/2015',
    'bornOnFarm': false,
    'movedOut': false
  },
  {
    'tag': '11005',
    'purpose': 'dairy',
    'category': 'cow',
    'breed': 'FR',
    'dob': '16/02/2017',
    'brand': '5',
    'inCalf': false,
    'served': false,
    'calved': false,
    'calfDate': null,
    'boughtIn': false,
    'boughtDate': null,
    'bornOnFarm': true,
    'movedOut': false
  },
  {
    'tag': '30745',
    'purpose': 'dairy',
    'category': 'cow',
    'breed': 'FR',
    'dob': '20/02/2011',
    'brand': '745',
    'inCalf': false,
    'served': false,
    'calved': false,
    'calfDate': null,
    'boughtIn': false,
    'boughtDate': null,
    'bornOnFarm': true,
    'movedOut': false
  },
  {
    'tag': '72765',
    'purpose': 'other',
    'category': 'cow',
    'breed': 'AYX',
    'dob': '10/03/2016',
    'brand': '765',
    'inCalf': false,
    'served': false,
    'calved': false,
    'calfDate': null,
    'boughtIn': true,
    'boughtDate': '06/08/2017',
    'bornOnFarm': false,
    'movedOut': false
  },
  {
    'tag': '71431',
    'purpose': 'other',
    'category': 'cow',
    'breed': 'AAX',
    'dob': '22/02/2012',
    'brand': '431',
    'inCalf': false,
    'served': false,
    'calved': false,
    'calfDate': null,
    'boughtIn': true,
    'boughtDate': '26/10/2015',
    'bornOnFarm': false,
    'movedOut': false
  },
  {
    'tag': '80039',
    'purpose': 'beef',
    'category': 'bull',
    'breed': 'LMX',
    'dob': '05/03/2014',
    'brand': '39',
    'boughtIn': false,
    'boughtDate': null,
    'bornOnFarm': true,
    'movedOut': false
  },
  {
    'tag': '80040',
    'purpose': 'dairy',
    'category': 'cow',
    'breed': 'FR',
    'dob': '22/01/2018',
    'brand': '39',
    'inCalf': false,
    'served': false,
    'calved': false,
    'calfDate': null,
    'boughtIn': false,
    'boughtDate': null,
    'bornOnFarm': true,
    'movedOut': false
  },
  {
    'tag': '80041',
    'purpose': 'beef',
    'category': 'cow',
    'breed': 'LMX',
    'dob': '01/02/2018',
    'brand': '39',
    'inCalf': false,
    'served': false,
    'calved': false,
    'calfDate': null,
    'boughtIn': false,
    'boughtDate': null,
    'bornOnFarm': true,
    'movedOut': false
  },
  {
    'tag': '80042',
    'purpose': 'beef',
    'category': 'cow',
    'breed': 'LMX',
    'dob': '11/02/2018',
    'brand': '39',
    'inCalf': false,
    'served': false,
    'calved': false,
    'calfDate': null,
    'boughtIn': false,
    'boughtDate': null,
    'bornOnFarm': true,
    'movedOut': false
  },
  {
    'tag': '80043',
    'purpose': 'dairy',
    'category': 'cow',
    'breed': 'FR',
    'dob': '05/03/2018',
    'brand': '39',
    'inCalf': false,
    'served': false,
    'calved': false,
    'calfDate': null,
    'boughtIn': false,
    'boughtDate': null,
    'bornOnFarm': true,
    'movedOut': false
  },
  {
    'tag': '80044',
    'purpose': 'beef',
    'category': 'bull',
    'breed': 'LMX',
    'dob': '16/03/2018',
    'brand': '39',
    'boughtIn': false,
    'boughtDate': null,
    'bornOnFarm': true,
    'movedOut': false
  }
];

export const GROUPS_OF_ANIMALS = [
  {
    'name': 'Group A',
    'created': '05/10/2017',
    'description': 'This is first group.',
    'animals': [
      '41626',
      '41051',
      '21281',
      '30412',
      '53911'
    ]
  },
  {
    'name': 'Test group',
    'created': '11/12/2017',
    'description': 'Just a test group.',
    'animals': [
      '11005',
      '30745',
      '72765',
      '71431'
    ]
  },
  {
    'name': 'Prepare to sell',
    'created': '24/12/2017',
    'description': 'Sell by Feb. 2018.',
    'animals': [
      '80040',
      '72765'
    ]
  }
];
